import { defineConfig } from 'oxlint'

export const base = defineConfig({
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'import', 'promise'],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    perf: 'warn',
    pedantic: 'off',
    restriction: 'off',
    style: 'off',
    nursery: 'off',
  },
  rules: {
    'array-callback-return': 'error',
    curly: ['error', 'all'],
    'default-case': 'off',
    'default-case-last': 'error',
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'func-style': 'off',
    'import/consistent-type-specifier-style': 'off',
    'import/exports-last': 'off',
    'import/extensions': 'off',
    'import/first': 'off',
    'import/group-exports': 'off',
    'import/no-anonymous-default-export': 'error',
    'import/no-commonjs': 'error',
    'import/no-cycle': ['warn', { ignoreTypes: true }],
    'import/no-default-export': 'off',
    'import/no-duplicates': ['error', { preferInline: false }],
    'import/no-relative-parent-imports': 'off',
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'off',
    'no-console': 'error',
    'no-debugger': 'error',
    'no-duplicate-imports': ['error', { allowSeparateTypeImports: true }],
    'no-else-return': 'error',
    'no-empty': 'error',
    'no-empty-function': 'off',
    'no-fallthrough': 'error',
    'no-implicit-coercion': 'off',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-magic-numbers': 'off',
    'no-nested-ternary': 'error',
    'no-new-object': 'error',
    'no-new-wrappers': 'error',
    'no-param-reassign': 'off',
    'no-plusplus': 'off',
    'no-promise-executor-return': 'error',
    'no-return-await': 'off',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: false,
        allowTaggedTemplates: false,
        allowTernary: false,
      },
    ],
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'off',
    'object-shorthand': ['error', 'properties'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'off',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    radix: 'error',
    'require-await': 'off',
    'sort-keys': 'off',
    'typescript/array-type': ['error', { default: 'array-simple' }],
    'typescript/ban-ts-comment': [
      'error',
      {
        'ts-expect-error': 'allow-with-description',
        'ts-ignore': true,
        'ts-nocheck': true,
        'ts-check': false,
        minimumDescriptionLength: 3,
      },
    ],
    'typescript/consistent-indexed-object-style': ['error', 'record'],
    'typescript/consistent-type-assertions': [
      'error',
      {
        assertionStyle: 'as',
        objectLiteralTypeAssertions: 'never',
      },
    ],
    'typescript/consistent-type-definitions': ['warn', 'type'],
    'typescript/consistent-type-exports': 'warn',
    'typescript/consistent-type-imports': [
      'error',
      {
        prefer: 'type-imports',
        fixStyle: 'separate-type-imports',
      },
    ],
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/method-signature-style': ['error', 'property'],
    'typescript/no-empty-function': 'off',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-inferrable-types': 'off',
    'typescript/no-namespace': ['error', { allowDefinitionFiles: true }],
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-restricted-types': [
      'error',
      {
        types: {
          Object: {
            message: 'Use object, unknown, or a more specific type instead.',
          },
          Function: {
            message: 'Use a specific function signature instead.',
          },
          Boolean: {
            message: 'Use boolean instead.',
            fixWith: 'boolean',
          },
          Number: {
            message: 'Use number instead.',
            fixWith: 'number',
          },
          String: {
            message: 'Use string instead.',
            fixWith: 'string',
          },
          Symbol: {
            message: 'Use symbol instead.',
            fixWith: 'symbol',
          },
        },
      },
    ],
    'typescript/no-useless-constructor': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-optional-chain': 'error',
    'unicorn/catch-error-name': ['error', { name: 'error' }],
    'unicorn/error-message': 'error',
    'unicorn/filename-case': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-null': 'off',
    'unicorn/no-useless-undefined': 'off',
    'unicorn/prefer-export-from': 'off',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-module': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-top-level-await': 'error',
  },
})
